fruits=["apple","banana","grape","pineapple"]
print('fruits: ' + str(fruits))
print('len(fruits): ' + str(len(fruits)))
print(fruits[0])
print('fruits[0]: ' + str(fruits[0]))
print(fruits[-1])
print('fruits[-1]: ' + str(fruits[-1]))
fruits.append("mango")
print('after append, fruits: ' + str(fruits))
print(fruits)
fruits.insert(0, "orange")
print('after insert, fruits: ' + str(fruits))
print(fruits)
fruits.remove("orange")
print('after remove, fruits: ' + str(fruits))
print(fruits)
del fruits[0]
print('after del, fruits: ' + str(fruits))
print(fruits)
value = fruits.pop()
print('after pop fruits: ' + str(fruits))
print('value: ' + value)